apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocm-cdoan-12345

commonAnnotations:
  cluster: cdoan-12345
  cluster-type: ocp
  version: "v0.0.1"

resources:
  - cloud-infrastructure-provisioning.pipelinerun.yaml

components:
  - ../../../bases/pipelines/cloud-infrastructure-provisioning
