apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - hello-world
  - cloud-infrastructure-provisioning
  - postgres-demo
  - cluster-bootstrap

commonAnnotations:
  version: "v0.0.1"