apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All cluster definitions (global + managed clusters)

resources:
  - global/

  - ocp-123/
  - ocp-234/
  - ocp-this-test-better-work/
