apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hub-provisioner

resources:
  - namespace.yaml
  - hub-provisioner.pipeline.yaml
  - cluster-remove.pipeline.yaml
  - bootstrap.pipeline.yaml
  - rbac.yaml
  - github-credentials.yaml

commonLabels:
  app.kubernetes.io/name: hub-provisioner
  app.kubernetes.io/component: pipeline
  app.kubernetes.io/part-of: bootstrap-infrastructure