apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocm-ocp-345

commonAnnotations:
  cluster: ocp-345
  cluster-type: ocp
  version: "v0.0.1"

resources:
  - cloud-infrastructure-provisioning.pipelinerun.yaml

components:
  - ../../../../bases/pipelines/cloud-infrastructure-provisioning
