apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocp-789-content
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  generators:
  - list:
      elements:
      - component: operators
        path: clusters/ocp-789/operators
        destination: https://api.ocp-789.bootstrap.red-chesterfield.com:6443
        syncWave: "10"
      - component: pipelines
        path: clusters/ocp-789/pipelines
        destination: https://api.ocp-789.bootstrap.red-chesterfield.com:6443
        syncWave: "20"
      - component: deployments
        path: clusters/ocp-789/deployments
        destination: https://api.ocp-789.bootstrap.red-chesterfield.com:6443
        syncWave: "30"
  
  template:
    metadata:
      name: ocp-789-{{component}}
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
      labels:
        cluster: ocp-789
        phase: content
    spec:
      project: default
      source:
        repoURL: https://github.com/openshift-online/bootstrap-hyperfleet
        path: '{{path}}'
        targetRevision: main
      destination:
        server: '{{destination}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
        - CreateNamespace=true
