kind: Kustomization

resources:
- ./advanced-cluster-management.application.yaml
- ./openshift-pipelines-operator.application.yaml
- ./vault.application.yaml
- ./regional-clusters.application.yaml
- ./regional-deployments.application.yaml
- ./regional-pipelines.application.yaml

