apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: ocp-foo
  namespace: ocp-foo
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    cloud: Amazon
    name: ocp-foo
    vendor: OpenShift
    region: us-west-2
  clusterName: ocp-foo
  clusterNamespace: ocp-foo
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  iamPolicyController:
    enabled: true
