apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: advanced-cluster-management-set
  namespace: openshift-gitops
spec:
  generators:
  - list:
      elements:
      - component: acm-operator
        path: bases/operators/advanced-cluster-management/overlays/release-2.14
        syncWave: "4"
      - component: acm-hub
        path: clusters/global/operators/advanced-cluster-management/base
        syncWave: "5"
      - component: acm-policies
        path: clusters/global/operators/gitops-integration
        syncWave: "6"
  template:
    metadata:
      name: acm-{{component}}
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/openshift-online/bootstrap
        path: '{{path}}'
        targetRevision: main
      destination:
        name: in-cluster
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
        syncOptions:
        - SkipDryRunOnMissingResource=true
        retry: # Extending the backoff / retry because ACM has to install before all CRs can finalize
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 3m