apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ocm-cluster-10

commonAnnotations:
  cluster: cluster-10
  cluster-type: ocp
  version: "v0.0.1"

resources:
  - ../global/overlays/pipelines-operator-only
  - namespace.yaml