apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: clm-ocp-mgt-01

commonAnnotations:
  cluster: ocp-mgt-01
  cluster-type: ocp
  version: "v0.0.1"

resources:
  - ../../../bases/operators/openshift-pipelines/overlays/pipelines-operator-only
