apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ocp-test-01-provisioning
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  generators:
  - list:
      elements:
      - component: cluster
        path: clusters/ocp-test-01/cluster
        destination: https://kubernetes.default.svc
        syncWave: "10"
  
  template:
    metadata:
      name: ocp-test-01-{{component}}
      namespace: openshift-gitops
      annotations:
        argocd.argoproj.io/sync-wave: '{{syncWave}}'
      labels:
        cluster: ocp-test-01
        phase: provisioning
    spec:
      project: default
      source:
        repoURL: https://github.com/openshift-online/bootstrap-hyperfleet
        path: '{{path}}'
        targetRevision: main
      destination:
        server: '{{destination}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
          allowEmpty: false
