apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  - openshift-gitops/
  - advanced-cluster-management/
  - openshift-pipelines-operator/
  - cluster-provisioning-metrics/ # monitors cluster provisioning
  - vault/
  - eso/
  - gitea/
  - cluster-bootstrap/

