apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  cluster: ocp-03
  cluster-type: ocp
  version: "v0.0.1"

resources:
  - ../global/overlays/pipelines-operator-only